### ISSUE TITLE
train details

### ISSUE THREAD

**Issue by ShungJhon** [neu-vi/OmniControl#1]
glad to see your good results of inserting control signal into the t2m model, hope it would be as useful as controlnet in the t2i field. And i’m curious about how do you train these two modules, like the data you used.

**Comment by ymingxie** [comment]
Thanks for your interest in our work! We used the HumanML3D and KIT datasets to train our method. Feel free to ask if you have more detailed training questions. The arxiv version will be updated soon and we will add more training details to it. The code will be released before 11/8/2023.

Thanks,
Yiming

**Comment by imabackstabber** [comment]
hi, any update? @ymingxie
