### ISSUE TITLE
About the training process of spatial guidance

### ISSUE THREAD

**Issue by CDLCHOI** [neu-vi/OmniControl#11]
Hello, I have a question about the training of spatial guidance.
The sampling process of spatial guidance is well described in your paper. 
But I'm confused on the training process.
The function is as follows：

def guide():
    x_t = self.q_sample(x_start, t, noise=noise)
    x_t = self.guide(x_t, t, model_kwargs=model_kwargs, train=True)
    model_output = model(x_t, t)

Could you explain why you put  **self.guide** here?
Is that a theoretical approach or empirical approach?
Waiting for you reply.   Thank you

**Comment by ymingxie** [comment]
Hi, Thanks for your interest in our work. It's more like an empirical approach. As mentioned in the paper, the spatial guidance only amends the position of the controlled joints and pelvis, and the learnable realism guidance is used to amend all other joints to ensure natural and reasonable human motion. So during training, we put spatial guidance before realism guidance to enforce the realism guidance can learn to amend the human motion which has been edited by spatial guidance.

**Comment by CDLCHOI** [comment]
Thank you very much ~!
