### ISSUE TITLE
Code release date

### ISSUE THREAD

**Issue by Steve-Tod** [neu-vi/OmniControl#2]
Hi,

Congrats on this great work! When will the code be public so that I can give it a try and use it in my project? Thank you!

Best,
Zhenyu

**Comment by ymingxie** [comment]
Thanks for your interest in our work! The code will be released before 11/8/2023. 

Thanks,
Yiming

**Comment by Steve-Tod** [comment]
Thanks, looking forward to that!

**Comment by ymingxie** [comment]
Hi Zhenyu,

Sorry for the delay in the code release. I am preparing the code and it should be ready tomorrow. 

Thanks,
Yiming

**Comment by Steve-Tod** [comment]
Thanks for the heads up! Looking forward to that!
