### ISSUE TITLE
A question about CG guidance

### ISSUE THREAD

**Issue by 2019211753** [neu-vi/OmniControl#20]
Classifier guidance was originally introduced to guide an unconditional model; however, OmniControl appears to apply this technique to guide a conditional model. Additionally, while classifier guidance is typically used during the sampling process, OmniControl employs it during training. Could you please help me understand this difference?

**Comment by ymingxie** [comment]
Hi, 

Conditional guidance isn’t limited to use with unconditional models. It can be applied to a conditional model with a new condition, such as spatial guidance, or with an existing condition, like text. While CG is typically utilized during the sampling process, we attempted to incorporate it during training, but it didn't provide any advantage. Therefore, you can skip this part and focus on using it during the inference stage.

Thanks

**Comment by 2019211753** [comment]
> Hi,
> 
> Conditional guidance isn’t limited to use with unconditional models. It can be applied to a conditional model with a new condition, such as spatial guidance, or with an existing condition, like text. While CG is typically utilized during the sampling process, we attempted to incorporate it during training, but it didn't provide any advantage. Therefore, you can skip this part and focus on using it during the inference stage.
> 
> Thanks

Thanks for your reply😄.
