### ISSUE TITLE
a question about spatial guidance

### ISSUE THREAD

**Issue by CDLCHOI** [neu-vi/OmniControl#3]
At the end of sec 3.1, you say "We still use the relative representations as input", so I think the x_t and x_0 should contain the axis-angle rotation of each joint, mu should have the same meaning as x_0 . 
But your spatial control signal is xyz positions, so how can axis-angle and xyz position calculate L2 distance?

Waiting for your reply. Thanks.

**Comment by CDLCHOI** [comment]
thanks！ close the issue now

**Comment by 2019211753** [comment]
> Thanks for your interest in our work! Yes, they did contain the axis-angle rotation of each joint in the relative representation. When calculating the L2 distance we convert it to global by using [this](https://github.com/GuyTevet/motion-diffusion-model/blob/af061ca7c7077fb144c0094a5a72932b967647b6/data_loaders/humanml/scripts/motion_process.py#L415). Note that the input/output in both motion diffusion model and realism guidance are in relative representation. But before it gets into the spatial guidance we will convert it to global first, so it can be compared with the given spatial control signal.
> 
> Hope this helps!
> 
> Thanks, Yiming

Can I understand that the spatial control used in the realism guidance module is based on relative location, while in the spatial guidance module it is based on absolute location?

**Comment by CDLCHOI** [comment]
> > Thanks for your interest in our work! Yes, they did contain the axis-angle rotation of each joint in the relative representation. When calculating the L2 distance we convert it to global by using [this](https://github.com/GuyTevet/motion-diffusion-model/blob/af061ca7c7077fb144c0094a5a72932b967647b6/data_loaders/humanml/scripts/motion_process.py#L415). Note that the input/output in both motion diffusion model and realism guidance are in relative representation. But before it gets into the spatial guidance we will convert it to global first, so it can be compared with the given spatial control signal.
> > Hope this helps!
> > Thanks, Yiming
> 
> Can I understand that the spatial control used in the realism guidance module is based on relative location, while in the spatial guidance module it is based on absolute location?

Both spatial Guidance and realism guidance use global absolute position. Their target is to get a correct relative position in motion representation

**Comment by 2019211753** [comment]
> > > Thanks for your interest in our work! Yes, they did contain the axis-angle rotation of each joint in the relative representation. When calculating the L2 distance we convert it to global by using [this](https://github.com/GuyTevet/motion-diffusion-model/blob/af061ca7c7077fb144c0094a5a72932b967647b6/data_loaders/humanml/scripts/motion_process.py#L415). Note that the input/output in both motion diffusion model and realism guidance are in relative representation. But before it gets into the spatial guidance we will convert it to global first, so it can be compared with the given spatial control signal.
> > > Hope this helps!
> > > Thanks, Yiming
> > 
> > 
> > Can I understand that the spatial control used in the realism guidance module is based on relative location, while in the spatial guidance module it is based on absolute location?
> 
> Both spatial Guidance and realism guidance use global absolute position. Their target is to get a correct relative position in motion representation

Get it. Thanks for your reply.
