### ISSUE TITLE
what is the differences between Mean_raw.npy in humanml_spatial_norm and Mean.npy in HumanML3D ?

### ISSUE THREAD

**Issue by takiee** [neu-vi/OmniControl#5]
![image](https://github.com/neu-vi/OmniControl/assets/83262562/e4097831-15c9-4d8f-b6a5-249d0fdc07bc)

**Comment by ymingxie** [comment]
Thank you for your interest in our work! Mean.npy is the mean of the *relative* positions of human joints following the [HumanML3D](https://openaccess.thecvf.com/content/CVPR2022/papers/Guo_Generating_Diverse_and_Natural_3D_Human_Motions_From_Text_CVPR_2022_paper.pdf) (Sec 5. Pose Representation). And the Mean_raw.npy is the mean of the *global* positions of human joints.

Thanks,
Yiming

**Comment by takiee** [comment]
Thanks for your answer! I would also like to ask what is the purpose of transforming hint through std and mean in the code guide function?

 hint = hint * self.raw_std + self.raw_mean

**Comment by takiee** [comment]
Thank you for your answer. Very meaningful work!
