### ISSUE TITLE
Can't generate an animated sample only with text input?

### ISSUE THREAD

**Issue by IgnazioGul** [neu-vi/OmniControl#7]
Hi, 

congratulations for your amazing work.

I am trying to generate a sample, only giving textual prompt.
As result, I always get a sample that is not doing any animation, besides slowly sliding with the entire body.:
https://github.com/neu-vi/OmniControl/assets/75915438/7fd8a115-7f1d-43dd-a2fd-3262d0fb7b2c

Do you know if this is a known issue and the actual behavior? 
### How to reproduce

Run the generate script as follows:
`
python -m sample.generate --model_path ./save/omnicontrol_ckpt/model_humanml3d.pt --output_dir ./issue-output/ --num_repetitions 3 --guidance_param 1  --text_prompt 'a person raises toolbox with the use of one hand'
`

**Comment by ymingxie** [comment]
Thank you for your feedback! I am checking it and will let you know soon.

**Comment by ymingxie** [comment]
Hi, thanks for your interest in our work. Please check our latest commit to fix this issue. 

Why does this issue occur? The MDM weights were not fixed during the training of the released checkpoint. Therefore, when generating samples with only text input, we still need to feed zeros as spatial signals to the realism guidance module.

Why not fix the MDM weights as ControlNet did? ControlNet fixed the original DM weights, which were trained on a large-scale dataset, to preserve the network's capability. Training MDM and OmniControl use the same dataset, HumanML3D, thus fixing MDM's weights is not necessary to preserve its capability. Moreover, in our experiments, joint training leads to better control performance.

**Comment by IgnazioGul** [comment]
I've tried out the last version of the model and everything works as it should, thank you for the fix.
